name: 'CI on tags & pushes to master, devel and v*-legacy'

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - devel
      - 'v*-legacy'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl on 3.0.1.11
      uses: coderus/github-sfos-build@old-stable
      with:
        release: 3.0.1.11
        arch: armv7hl

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results
        path: RPMS/
